name: ReleaseArviZ

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New major, minor, patch or custom release'
        options: 
        - major
        - minor
        - patch
        - custom
        required: true
      custom_version:
        description: 'New custom release version'
        required: false

jobs:
  release-arviz:
    name: Publish release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
      fail-fast: false
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      
      - name: Current version
        run: | 
          echo "CURRENT_ARVIZ_VERSION=$(sed -n 's/^.*__version__\s*=\s*\"\(.*\)\"\.*$/\1/p' arviz/__init__.py)" >> $GITHUB_ENV
        
        
      - name: Split current version
        run: | 
          echo "ARVIZ_OLD_MAJOR=$(echo ${{ env.CURRENT_ARVIZ_VERSION }} | sed -n 's/\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)/\1/p')" >> $GITHUB_ENV
          echo "ARVIZ_OLD_MINOR=$(echo ${{ env.CURRENT_ARVIZ_VERSION }} | sed -n 's/\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)/\2/p')" >> $GITHUB_ENV
          echo "ARVIZ_OLD_PATCH=$(echo ${{ env.CURRENT_ARVIZ_VERSION }} | sed -n 's/\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)/\3/p')" >> $GITHUB_ENV
          
          
      - name: Calculate the new version
        if: "contains(github.event.inputs.new_version, 'major')"
        run: |
          echo "NEW_ARVIZ_VERSION_M=$(echo $((${{ env.ARVIZ_OLD_MAJOR }} + 1)).${{ env.ARVIZ_OLD_MINOR }}.${{ env.ARVIZ_OLD_PATCH }})" >> $GITHUB_ENV
          echo "NEW_ARVIZ_VERSION_MM=$(echo ${{ env.ARVIZ_OLD_MAJOR }}.$((${{ env.ARVIZ_OLD_MINOR }} + 1)).${{ env.ARVIZ_OLD_PATCH }})" >> $GITHUB_ENV
          echo "NEW_ARVIZ_VERSION_MMM=$(echo ${{ env.ARVIZ_OLD_MAJOR }}.${{ env.ARVIZ_OLD_MINOR }}.$((${{ env.ARVIZ_OLD_PATCH }} + 1)))" >> $GITHUB_ENV
          
      - name: Calculate the new version
        run: |
          echo ${{ env.NEW_ARVIZ_VERSION_M }}
          echo ${{ env.NEW_ARVIZ_VERSION_MM }}
          echo ${{ env.NEW_ARVIZ_VERSION_MMM }}
