name: test_run

on: [push, pull_request]

jobs:
  tests:
    name: tests
    timeout-minutes: 20
    runs-on: ${{ matrix.runs-on }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - {runs-on: ubuntu-20.04, python-version: 3.9}
          - {runs-on: ubuntu-20.04, container: "ubuntu:latest", python-version: 3.8}
          - {runs-on: ubuntu-20.04, container: "fedora:latest", python-version: 3.8}
          - {runs-on: ubuntu-20.04, container: "debian:bullseye", python-version: 3.8}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print compiler versions
        run: |
          gcc --version || true
          clang --version || true

      - name: Print info
        run: cat /etc/os-release

      - name: install something
        run: python3 -m pip install "poetry~=1.1.4"
